### ISSUE TITLE
Getting error when trying to import chapters from description file

### ISSUE THREAD

**Issue by Zeckro** [alan1world/yt_chapters#1]
Description:
When executing yt_chapters.py --fix "https://youtu.be/pyk9tip64KY", the following error occurs:
[youtube] pyk9tip64KY: Downloading webpage
[info] Writing video description to: Microsoft has an Xbox Handheld!.description
[download] Destination: Microsoft has an Xbox Handheld!.f401.mp4
[download] 100% of 273.98MiB in 00:31
[download] Destination: Microsoft has an Xbox Handheld!.f140.m4a
[download] 100% of 6.00MiB in 00:00
[ffmpeg] Merging formats into "Microsoft has an Xbox Handheld!.mp4"
Deleting original file Microsoft has an Xbox Handheld!.f401.mp4 (pass -k to keep)
Deleting original file Microsoft has an Xbox Handheld!.f140.m4a (pass -k to keep)
Fix the description file to have the chapters on their own lines in the format timecode name and then press Enter to continue...
[Chapter import] Guessed video frame rate 30000/1001
Saving Microsoft has an Xbox Handheld!.mp4: 0.500 secs Interleaving
[Core] system failure for file opening of "out_Microsoft has an Xbox Handheld!.mp4" in mode "w+b": 0x00000005
Error: I/O Error

        Error: I/O Error

I'm trying this with and without fixing the timestamps so that they are in one line each and get the same error.

Additional information:

Windows 10
youtubedl, ffmpeg and MP4Box in path directory

**Comment by alan1world** [comment]
This looks to be a Windows error where it is losing track of the output file.  
I've tested it the link you've given on my machine (Linux, Python 3.9) and it worked perfectly.

What I'd suggest is that you comment out the last two lines and see if the chapter file exists on disk. If so, check if the file can be manually merged using MP4Box.

It could be an issue with where the script is being run from. It saves the files in same directory as the current context. Probably would have been better to have pointed it to a `tempfile` location which maybe would avoid location-based errors.

**Comment by Zeckro** [comment]
You are right, it is a directory issue. I tried the same with the folder directly on drive D (D:/yt_chapters-main) and it worked. It was located in the standard Documents folder before. Weird.
Thanks for the help!

**Comment by alan1world** [comment]
In Win 10 the Documents folder is virtualised, and the permissions are a little weird. Python installations on Windows can also sometimes be a little strange. It's possible python isn't running with the same account permissions as your user account which would explain it running against the external directory.

Thanks for confirming what was going on.
