### ISSUE TITLE
Cannot split video have stdout=''

### ISSUE THREAD

**Issue by namlhse02285** [alan1world/yt_chapters#2]
Hi. I'm trying to download this video "https://www.youtube.com/watch?v=Sd3y_kr1A6M" but it throw exception that cannot parse to float line 100(because stdout of ffprobe is empty)
Tried to fix(use ffmpeg.exe instead of ffprobe .exe, it can grab duration) but it throw other exception

**Comment by alan1world** [comment]
You don't say what operating system you are using, nor what version of Python.  
In the future please include these details, together with the *full* error details.

I have tested the link above and it works perfectly on my setup (Linux x64, Python 3.9).  
This means it is something in your setup that is incorrect.

The subprocess code here only calls "ffprobe" and not "ffprobe.exe". You may need to change that in order for it work properly on Windows. You will also need to make sure that ffprobe is in your Windows path, or change it to a full reference to the executable (e.g. "C:\Program Files\ffmpeg\ffprobe.exe").

Note that in your text above, "ffprobe .exe" is incorrect as there is a space between "ffprobe" and ".exe". That space should not be there.

**Comment by namlhse02285** [comment]
Thanks for rep.
OS: Windows 10 x64
Python: 3.9.7

Sorry for the lack of info, I just did manage to run fine by now.
The problem is: I did modify all ffprobe and ffmpeg to full reference to the executable, but ffmpeg still have to be in PATH of Environment Variables, because youtube-dl need it to combine all video parts into one.

Thanks for good application, I appreciate.
