### ISSUE TITLE
UnicodeDecodeError: 'cp932' illegal multibyte sequence

### ISSUE THREAD

**Issue by namlhse02285** [alan1world/yt_chapters#3]
OS: Windows x64
Python version: 3.9.7
youtube link: https://www.youtube.com/watch?v=we067drlrXM

Seem like if video comment have some weird character inside make this tool cannot decode. Result is video was downloaded but no timestamp.
Console:
```
F:\game\NFS no limit\tool_download_youtube>python yt_chapters --split "https://www.youtube.com/watch?v=we067drlrXM"
[youtube] we067drlrXM: Downloading webpage
[info] Writing video description to: Breakout (Volkswagen Scirocco R) - Day 2 (Evasion) _ Need For Speed -No Limits - Special Event Guide.description
[download] Destination: Breakout (Volkswagen Scirocco R) - Day 2 (Evasion) _ Need For Speed -No Limits - Special Event Guide.f137.mp4
[download] 100% of 209.15MiB in 00:46
[download] Destination: Breakout (Volkswagen Scirocco R) - Day 2 (Evasion) _ Need For Speed -No Limits - Special Event Guide.f140.m4a
[download] 100% of 9.39MiB in 00:01
[ffmpeg] Merging formats into "Breakout (Volkswagen Scirocco R) - Day 2 (Evasion) _ Need For Speed -No Limits - Special Event Guide.mp4"
Deleting original file Breakout (Volkswagen Scirocco R) - Day 2 (Evasion) _ Need For Speed -No Limits - Special Event Guide.f137.mp4 (pass -k to keep)
Deleting original file Breakout (Volkswagen Scirocco R) - Day 2 (Evasion) _ Need For Speed -No Limits - Special Event Guide.f140.m4a (pass -k to keep)
Traceback (most recent call last):
  File "F:\game\NFS no limit\tool_download_youtube\yt_chapters", line 141, in <module>
    chapters = get_best_mp4_single_file(download_source=link_to_download,
  File "F:\game\NFS no limit\tool_download_youtube\yt_chapters", line 28, in get_best_mp4_single_file
    return read_description_file(description_file=description_file)
  File "F:\game\NFS no limit\tool_download_youtube\yt_chapters", line 59, in read_description_file
    for line in f:
UnicodeDecodeError: 'cp932' codec can't decode byte 0x85 in position 1039: illegal multibyte sequence
```

Edit1: I found solution to fix this, just force encoding to utf-8, change line 55 from
`with open(description_file, 'r') as f:` to `with open(description_file, 'r', encoding="utf-8") as f:`

**Comment by alan1world** [comment]
'cp932' is the Japanese code page.  
The character at 1039 looks like it's the bullet symbol. Which is a bit of a surprise but character decode is complicated.

I don't know enough about the Japanese Windows code page to say why it would fail on this - it works fine when the end to end process is Unicode. Most UTF-8 issues I've encountered before are not actually the symbol, it's a combination of the symbol and the one before or after (hence the "multibyte sequence").

Using `open(description_file, 'r', encoding="utf-8")` is a good suggestion, if the base system is not UTF-8 (i.e. a Windows code page is set).

**Comment by namlhse02285** [comment]
I did check the encoding by python before and it's still utf-8, idk why it use cp932 though...
```
# Importing sys module 
import sys 
  
# Using sys.getdefaultencoding() method 
encoding = sys.getdefaultencoding() 
  
# Print the current string encoding used 
print(encoding)
```
Result: utf-8

**Comment by alan1world** [comment]
Why? No idea! Python 3 is meant to be UTF strings and if you tag the file as UTF, it would make sense for it to stay in UTF.  
I've encountered similar problems before and character encoding issues are a pain sometimes to resolve.

Anyway, you found your solution, thank you for sharing it.

Edit: It looks like it thinks your system is UTF, which modern systems should be if set up correctly. My best guess at this point is that it ran down a list of encodings, guessed it was cp932 (or cp932 was the last on the list) and failed to decode it, raising the exception.
