### ISSUE TITLE
am I doing something wrong?

### ISSUE THREAD

**Issue by Bestusername7171** [alan1world/yt_chapters#6]
![download](https://user-images.githubusercontent.com/98695214/151702565-69e74285-c608-4c34-89aa-9074ce3f79f1.png)

What exactly am I doing wrong? I just want to download this song " https://www.youtube.com/watch?v=OWjudyW7RGE&t"

And what I did to try to run the script is, to create a notepad file, name it yt_chapters.py and run that through Python.

How the hell can I do it right? :(

**Comment by alan1world** [comment]
> what I did to try to run the script is, to create a notepad file, name it yt_chapters.py and run that through Python

Hopefully you copied the code into the file?
If you are not working from a git-clone, you should be copying [the raw code](https://raw.githubusercontent.com/alan1world/yt_chapters/main/yt_chapters) and not the section with github's nice reading layout.

I trust you have installed the requirements necessary for the code to run as per the [Readme](https://github.com/alan1world/yt_chapters/blob/main/README.md)

Do you have py files associated to run with Python? If not, like any application you will need to pass the full path, including the interpreter

**Comment by Bestusername7171** [comment]
> > what I did to try to run the script is, to create a notepad file, name it yt_chapters.py and run that through Python
> 
> Hopefully you copied the code into the file? If you are not working from a git-clone, you should be copying [the raw code](https://raw.githubusercontent.com/alan1world/yt_chapters/main/yt_chapters) and not the section with github's nice reading layout.
> 
> I trust you have installed the requirements necessary for the code to run as per the [Readme](https://github.com/alan1world/yt_chapters/blob/main/README.md)
> 
> Do you have py files associated to run with Python? If not, like any application you will need to pass the full path, including the interpreter

I copied the code into a notepad, named it yt_chapters.py and double clicked, then I did the command for download and an error came across...Can u explain me how I do it correctly?

**Comment by alan1world** [comment]
When you save a file in notepad, it appends ".txt" onto the filename. The filename you saved it as isn't "yt_chapters.py", it's "yt_chapters.py.txt" and that is why the system cannot find a file named "yt_chapters.py".

**Comment by Bestusername7171** [comment]
> n you save a file in notepad, it appends ".txt" onto the filename. The filename you saved it as isn't "yt_chapters.py", it's "yt_chapters.py.txt" and that is why the system cannot find a file named "yt_chapters.py".

Huh? How then???? How do I save it as .py and not txt.py.

**Comment by alan1world** [comment]
In Windows Explorer, under View menu, make sure the "File name extensions" checkbox is ticked.
Then you can rename "yt_chapters.py.txt" to "yt_chapters.py".
